### ISSUE TITLE
The extension broke with today's Nightly update.

### ISSUE THREAD

**Issue by SirNeon** [m-khvoinitsky/dark-background-light-text-extension#88]
Nightly Linux 56.0a1 (2017-07-25) (64-bit)

The colors stopped applying to web pages and when I try to access the global preferences page I get the following:

```
Access to the file was denied

The file at resource://jid1-qofqdk4qzufgwq-at-jetpack/data/preferences.html is not readable.

    It may have been removed, moved, or file permissions may be preventing access.
```

**Comment by bemug** [comment]
Same here.
Nightly 56.0a1 (2017-07-25) (64-bit)

**Comment by m-khvoinitsky** [comment]
I've just tested it on GNU\Linux with latest nightly at the moment (2017-07-30) and the 2017-07-25 and it works on both.
Is there still someone who experience this issue? Can you please provide some additional information:
* Operating System
* Browser Console output (Menu → Developer → Browser Console)
* Whether it reproduces or not on a fresh profile

**Comment by SirNeon618** [comment]
Yes I'm still experiencing this. It reproduces on a new profile. I'm using Debian.

When trying to open the global preferences page:

```
Use of nsIFile in content process is deprecated.  loader.js:247:15
NS_ERROR_FILE_ACCESS_DENIED: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIZipReaderCache.getZip]  loader.js:249
```

Another error I get with when loading new pages is:

```
TypeError: can't access dead object
Stack trace:
load_into_window@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-qofqdk4qzufgwq-at-jetpack/lib/process-script.js:82:1
load_into_window/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-qofqdk4qzufgwq-at-jetpack/lib/process-script.js:107:28
notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
  timers.js:43
```

**Comment by m-khvoinitsky** [comment]
> TypeError: can't access dead object

This is known issue, it happens while unloading previous page, not when loading new (you have to unload previous page before loading new)

> Use of nsIFile in content process is deprecated

That's warning, not error, It's also here for a long time.

> NS_ERROR_FILE_ACCESS_DENIED: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIZipReaderCache.getZip]  loader.js:249

That's looks like the reason. It seems related to this changes https://bugzilla.mozilla.org/show_bug.cgi?id=1383215
However, I still can not reproduce it. Do you have something additional to say about your setup?

**Comment by SirNeon618** [comment]
All I've done with my setup is flip a few options in about:config to enable Stylo/privacy protection/hardware acceleration, but it doesn't work when I use a new profile either.

**Comment by Dxhs** [comment]
I've got this problem too. Untill I went on git, I did a full reset and the common fixit bs. Nothing worked.
56.0a1 (2017-07-30) (64-bit) (Linux)

**Comment by SirNeon618** [comment]
I just noticed that the colors still apply to extension pop-ups when you click on their icons.

**Comment by Dxhs** [comment]
New linux install, new PC, same results :(

Linux Mint 18.2 64bit
Kernel: 4.8.0-53-generic
Firefox Nightly 56.0a1 (2017-08-01) (64-bit)

```
Access to the file was denied

The file at resource://jid1-qofqdk4qzufgwq-at-jetpack/data/preferences.html is not readable.
It may have been removed, moved, or file permissions may be preventing access.
```

It's working on "normal" Firefox, idk what's happening with Nightly..

**Comment by m-khvoinitsky** [comment]
> I just noticed that the colors still apply to extension pop-ups when you click on their icons.

What happens if you disable e10s?

Just tried latest Nightly on Debian (which is 57 already!) and it still works.
Could someone post an exact link of Nightly in which you experience an issue (just in case because I have no idea what else to try).

**Comment by SirNeon618** [comment]
> What happens if you disable e10s?

It fixes the issue entirely. The colors apply as expected and I can access the global preferences page.

**Comment by m-khvoinitsky** [comment]
Finally, I've reproduced it.

The problem was that I always create temporary profile in /tmp/ to test something and launch it this way:
```bash
./firefox/firefox --no-remote --profile /tmp/nightly/
```
Meanwhile, the problem seems to be related to the fact that Firefox content processes have been restricted access to $HOME (where usually profiles located). That's why I wasn't unable to reproduce it.

**Comment by SirNeon** [comment]
After today's Nightly update, the extension is now working as expected again. I guess they fixed whatever was causing the problem?

**Comment by Dxhs** [comment]
> After today's Nightly update

This one? 
`Firefox Nightly, August 2, 2017 57.0a1`

**Comment by Dxhs** [comment]
> After today's Nightly update

What version is that?

**Comment by SirNeon** [comment]
> What version is that?

57.0a1 (2017-08-08) (64-bit)

**Comment by bemug** [comment]
Confirmed working on 57.0a1 (2017-08-08) (64-bit)

**Comment by SkyWheel** [comment]
Today's update for Firefox Nightly for Android (57.0a1 12.08.2017) has broken the addon :( 
Temporarily have to use Firefox stable instead...

**Comment by Kewjoe** [comment]
This addon just broke on Firefix Developer Edition 56.0b2 (64-bit). Running on Linux Mint 18.2.

**Comment by m-khvoinitsky** [comment]
My [previous guess](https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/88#issuecomment-318909203) was wrong. 

The real cause were changesets:
```
Due to skipped revisions, the first bad revision could be any of:
changeset:   370755:167f91f87172
user:        Gian-Carlo Pascutto <gcp@mozilla.com>
date:        Mon Jul 24 16:32:22 2017 +0200
summary:     Bug 1308400 - Support file process, whitelist path prefs. r=jld

changeset:   370756:84b1aafdc1c2
user:        Gian-Carlo Pascutto <gcp@mozilla.com>
date:        Thu Jul 06 15:31:13 2017 +0200
summary:     Bug 1308400 - Symlink handling for read brokering. r=jld
```
which link to issue https://bugzilla.mozilla.org/show_bug.cgi?id=1308400 about implementing sandboxing which makes sense according to [my observations](https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/88#issuecomment-320325668).

This has been fixed in [https://bugzilla.mozilla.org/show_bug.cgi?id=1385891](https://bugzilla.mozilla.org/show_bug.cgi?id=1385891): 
```
changeset:   373177:55b494574257
user:        Gian-Carlo Pascutto <gcp@mozilla.com>
date:        Fri Aug 04 09:48:32 2017 +0200
summary:     Bug 1385891 - Whitelist things in the extension dir, not just the dir itself. r=jld
```

**Comment by m-khvoinitsky** [comment]
Further breakage happened already with 57.0a which is valid because legacy extensions should not work there.

Until WebExtensions port will be done all you can do is use at most Firefox 56.

**Comment by SkyWheel** [comment]
@m-khvoinitsky , it still doesn't work on Firefox Nightly for Android (57.0a1 2017-08-20)

**Comment by SkyWheel** [comment]
Oops. I beg your pardon. Didn't read the previous message, sorry.

**Comment by SirNeon** [comment]
> Until WebExtensions port will be done all you can do is use at most Firefox 56.

How long until the WebExtensions port is ready?

**Comment by m-khvoinitsky** [comment]
> How long until the WebExtensions port is ready?

Hopefully, I'll upload it to beta channel at the end of the week.
However, there are [some issues](https://discourse.mozilla.org/t/webextensions-porting-access-to-cross-origin-document-stylesheets-cssrules/18359).
